# Define and sync repository labels
- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: chore
  color: cfd3d7
  description: CI, tooling, or maintenance
- name: dependencies
  color: 0366d6
  description: Updates to dependencies
- name: ci
  color: 1d76db
  description: Continuous integration and workflows
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: security
  color: ee0701
  description: Security-related changes or reports
