name: Sync labels

on:
  push:
    branches: ['main']
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v5
      - name: Sync labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          dry-run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
